outdir: data/outputs/examples/hetero_robin

fem:
  case: hetero
  left_type: dirichlet
  right_type: robin
  u0: 0.0
  H_right: 10.0         # Robin coefficient h (right end)
  G_right: 0.0          # Robin inhomogeneity g

pinn:
  epochs: 2000
  w_bc: 100
  lr: 1.0e-3
  ncol: 300
  snap: 20
  seed: 1
  normalize_x: true
  normalize_u: true

dataset:
  n_configs: 40
  M: 40
  P_low: 0.2
  P_high: 1.0
  sigma: 0.03
  seed: 1

bb:
  epochs: 2000
  lr: 1.0e-3
  width: 64
  depth: 4
  snap: 20

hero:
  enabled: true
