outdir: data/outputs/examples/tip_extrap

fem:
  case: tip_load
  left_type: dirichlet
  right_type: neumann
  u0: 0.0
  PL: 1.20   # outside dataset range

pinn:
  epochs: 1200
  w_bc: 100
  lr: 1.0e-3
  ncol: 200
  snap: 20
  seed: 0
  normalize_x: true
  normalize_u: true

dataset:
  n_configs: 40
  M: 40
  P_low: 0.2
  P_high: 1.0
  sigma: 0.02
  seed: 0

bb:
  epochs: 1200
  lr: 1.0e-3
  width: 64
  depth: 4
  snap: 20

hero:
  enabled: true
